name = "FlightGNC"
uuid = "f141b7d0-6781-47a7-9266-a0707263841d"
authors = ["Namhoon Cho <nhcho91@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
FSimBase = "731e945d-f3ed-49a1-bee2-3998705ef155"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
julia = "1.6, 1.7, 1.8"
ComponentArrays = "0.10, 0.11, 0.12, 1"
FSimBase = "0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1"
Plots = "1"
Reexport = "1"
UnPack = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
